### ISSUE TITLE
Regarding predictionCount in `Prediction.sol`

### ISSUE THREAD

**Issue by 0xScratch** [KristofferGW/flowback-onchain#21]
As per @KristofferGW request, I checked Prediction.sol and found the error which at first seems tricky to me. But then realised maybe even others missed something like I did. But anyways, the error got figured out. Gonna show three code snippets which will clarify it well:

This is the way `proposals` has been declared inside `Polls.sol`. In this mapping, `uint` works as a key and value is a dynamic array `Proposal[]` which contains elements of `Struct Proposal`
```
mapping(uint => Proposal[]) public proposals;
```

Here's the way data is been pushed inside this mapping. First access the key which points to the value `array` and then push the struct we want. Been taken from `Poll.sol` on line 76
```
proposals[_pollId].push(Proposal({
            description: _description,
            voteCount: 0,
            proposalId: _proposalId,
            predictionCount: 0
 }));
```

Now, the important part. This is the way `PredictionCount` was been incremented in `Prediction.sol` which is clearly wrong if you notice all three code snippets.
```
proposals[_proposalId].predictionCount++;
```
You must be noticing that we aren't targeting the elements inside the dynamic array which is pointed by the key `_proposalId`. 
But if we try to change the line to `proposals[_proposalId][0].predictionCount++`, then yes it do works but gonna target the first element of `Proposal` array.

Hope you get it. I be happy to answer any further questions.

Thanks!

**Comment by EllenLng** [comment]
Okay i see! Thanks for your knowledge, really appreciate it, we are currently about to graduate as blockchain developers at Medieinstitutet so it would be superb if we could shoot you some questions if they pop up!

Thanks and best regards!!

**Comment by 0xScratch** [comment]
Always welcome!
