### ISSUE TITLE
Proposal: Foundry Tests should be included

### ISSUE THREAD

**Issue by 0xScratch** [KristofferGW/flowback-onchain#31]
Hey @EllenLng @KristofferGW 

Hope you guys are doing great! 
It's better if we start creating tests using Foundry side by side as this repo grows. It's always essential to test the smart contracts and  Foundry sounds perfect. 
What's your say about it?

**Comment by EllenLng** [comment]
Hello! 
Yes it seems like a great idea! 
We have been working with hardhat before but Foundry might be better in this repo. We will look into that today!

**Comment by 0xScratch** [comment]
Hey @EllenLng 
Just made some changes related to repo structure which kind of suits up with `foundry`. Also improved `README` a little bit.
[Check it out](https://github.com/Aryan9592/flowback-onchain/tree/foundry-tests)

**Comment by EllenLng** [comment]
I also started with it yesterday, but yours looks much better, feel free to pr.

**Comment by 0xScratch** [comment]
Sure!
